version: 2.1

orbs:
  ruby: circleci/ruby@2.5.3

executors:
  default:
    macos:
      xcode: 16.3.0

jobs:
  doc:
    executor: default
    steps:
      - checkout
      - ruby/install:
          version: "3.4.4"
      - ruby/install-deps
      - run: bundle exec yard doc
  rspec:
    executor: default
    steps:
      - checkout
      - ruby/install:
          version: "3.4.4"
      - ruby/install-deps
      - ruby/rspec-test
  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install:
          version: "3.4.4"
      - ruby/install-deps
      - ruby/rubocop-check
  release:
    executor: default
    steps:
      - checkout
      - ruby/install:
          version: "3.4.4"
      - ruby/install-deps
      - run: bundle exec rake release

workflows:
  version: 2.1
  build:
    jobs:
      - doc
      - rspec
      - rubocop
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
