#!/usr/bin/env ruby
# frozen_string_literal: true

# !/usr/bin/env ruby

require "bundler/setup"
require "macos"

display = MacOS.display

puts "#{display.bounds.width}×#{display.bounds.height}"

display.screenshot do |tempfile|
  `open -a Preview "#{tempfile.path}"`
  sleep 5
end
