#!/usr/bin/env ruby
# frozen_string_literal: true

# !/usr/bin/env ruby

require "bundler/setup"
require "macos"

keyboard = MacOS.keyboard

keyboard.type("abcdefghijklmnopqrstuvwxyz")
keyboard.keys("return")
keyboard.type("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
keyboard.keys("return")
keyboard.type("1234567890")
keyboard.keys("return")
